# Generated by Django 5.1 on 2024-09-13 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0014_alter_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
    ]
