# Generated by Django 5.1 on 2024-09-28 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0025_todo_shared_with'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='shared_with',
        ),
    ]
